// Package roster renders the seat dispatch table as a v1-cascade source:
// every agent self-selects its identity by harness and role at launch.
package roster

import (
	"bytes"
	_ "embed"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/coilyco/agent-compose/v2/internal/person"
	"github.com/coilyco/agent-compose/v2/internal/schema"
)

//go:embed definitions/NATIVE-ADAPTATION.txt
var nativeAdaptationPolicy string

// Render produces the artifact file set.
func Render(p *person.Person, sources []*schema.Source, _ string) (map[string][]byte, error) {
	personSource, err := person.Source(p)
	if err != nil {
		return nil, err
	}
	sources = append([]*schema.Source{personSource}, sources...)

	snapshot, err := person.MarshalSnapshot(p)
	if err != nil {
		return nil, err
	}
	snapshotV4, err := person.MarshalSnapshotV4(p)
	if err != nil {
		return nil, err
	}
	files := map[string][]byte{"person.json": snapshot, "person.v4.json": snapshotV4}
	bodies := personalityBodies(p, sources)
	instructions, err := instructionBodies(sources)
	if err != nil {
		return nil, err
	}

	var table strings.Builder
	table.WriteString("<!-- generated by agent-compose roster; do not edit -->\n\n")
	for _, body := range instructions {
		table.Write(body)
		if len(body) > 0 && body[len(body)-1] != '\n' {
			table.WriteString("\n")
		}
		table.WriteString("\n")
	}
	table.WriteString("# Agent seats\n\n")
	table.WriteString("Each agent resolves its role origin once at session start. If launch context\n")
	table.WriteString("assigns a role, the agent treats that assignment as authoritative. Otherwise,\n")
	table.WriteString("an unassigned native agent uses the initial substantive request as a soft\n")
	table.WriteString("signal and selects the closest role. Later task shape does not change the role.\n")
	table.WriteString("An eligible inferred native role changes only under the explicit policy below.\n")
	table.WriteString("Before acting, each agent loads the selected role skill and every personality\n")
	table.WriteString("skill named by that role's complete ordered boundary. Other role and personality\n")
	table.WriteString("skills stay inactive unless the native interactive policy activates them. Role\n")
	table.WriteString("methods stay lazy and apply only when the active role and task both match.\n\n")
	table.WriteString(renderNativeAdaptationPolicy(p))

	for _, roleName := range p.RoleOrder {
		role := p.Roles[roleName]
		if len(role.Seats) == 0 {
			continue
		}
		card, err := p.RenderRoleIdentityCard(roleName, role.FavoriteColor, p.RoleActiveBoundaries(roleName))
		if err != nil {
			return nil, err
		}
		table.WriteString("\n")
		table.WriteString(card)
		table.WriteString("\n")
		if role.CopyContract != nil {
			fmt.Fprintf(&table, "Copy contract (%s):\n", role.CopyContract.Scope)
			for _, rule := range role.CopyContract.Rules {
				fmt.Fprintf(&table, "* prefer %s for %s\n", rule.Prefer, rule.Forbid)
			}
			table.WriteString("\n")
		}
		raw, ok := p.RoleSkillDefinition(roleName)
		if !ok {
			return nil, fmt.Errorf("render role %q: role skill is missing", roleName)
		}
		files[".agents/skills/"+p.RoleSkillID(roleName)+"/SKILL.md"] = raw
		for _, method := range role.Methods {
			raw, ok := p.RoleMethodDefinition(roleName, method)
			if !ok {
				return nil, fmt.Errorf("render role %q: method skill %q is missing", roleName, method)
			}
			files[".agents/skills/"+method+"/SKILL.md"] = raw
		}
		for _, boundary := range p.RoleActiveBoundaries(roleName) {
			raw, ok := p.BoundarySkillDefinition(boundary)
			if !ok {
				return nil, fmt.Errorf("render role %q: boundary skill %q is missing", roleName, boundary)
			}
			files[".agents/skills/"+p.Boundaries[boundary].Skill+"/SKILL.md"] = raw
		}
		if role.Guardrail != "" {
			raw, ok := p.GuardrailSkillDefinition(role.Guardrail)
			if !ok {
				return nil, fmt.Errorf(
					"render role %q: guardrail skill %q is missing", roleName, role.Guardrail)
			}
			files[".agents/skills/"+p.Guardrails[role.Guardrail].Skill+"/SKILL.md"] = raw
		}
	}
	files["AGENTS.COMPOSE.md"] = []byte(table.String())

	files["AGENTS.claude.md"] = []byte(
		"## Lazy-loaded identity doctrine\n\n" +
			"Agent-compose installs role and personality definitions as skills. " +
			"The selected identity card names the exact skills the agent reads before acting.\n",
	)

	for name, body := range bodies {
		files[".agents/skills/"+p.Personalities[name].Skill+"/SKILL.md"] = body
	}
	files["personality-index.md"] = []byte(personalityIndex(p))
	return files, nil
}

func renderNativeAdaptationPolicy(p *person.Person) string {
	var slugs []string
	for _, roleName := range p.RoleOrder {
		if len(p.Roles[roleName].Seats) > 0 {
			slugs = append(slugs, "`"+roleName+"`")
		}
	}
	available := "none"
	if len(slugs) > 0 {
		available = strings.Join(slugs, ", ")
	}
	return strings.Replace(
		nativeAdaptationPolicy,
		"{{ROLE_SLUGS}}",
		available,
		1,
	)
}

func personalityIndex(p *person.Person) string {
	v4, err := person.BuildSnapshotV4(p)
	if err != nil {
		return ""
	}
	var out strings.Builder
	out.WriteString("# Personality index\n\n")
	for _, name := range sortedPersonalities(p) {
		entry := v4.Personalities[name]
		fmt.Fprintf(&out, "## %s\n\n", name)
		if len(entry.Aliases) > 0 {
			fmt.Fprintf(&out, "Aliases: %s\n\n", strings.Join(entry.Aliases, ", "))
		}
		fmt.Fprintf(&out, "Source: %s\n\n", entry.SourceLibrary)
		if len(entry.Affinities) == 0 {
			out.WriteString("Roles: none\n\n")
			continue
		}
		for _, affinity := range entry.Affinities {
			fmt.Fprintf(&out, "* %s - %s\n", affinity.Role, strings.Join(affinity.Personalities, ", "))
		}
		out.WriteByte('\n')
	}
	return out.String()
}

// instructionBodies preserves source order and rejects divergent copies of a
// shared instruction, matching bundle resolution at the host roster boundary.
func instructionBodies(sources []*schema.Source) ([][]byte, error) {
	selected := map[string][]byte{}
	var bodies [][]byte
	for _, src := range sources {
		for _, instruction := range src.Instructions {
			raw, err := src.ReadFile(instruction.Path)
			if err != nil {
				return nil, fmt.Errorf("source %q instruction %q: %w", src.ID, instruction.ID, err)
			}
			if prior, ok := selected[instruction.ID]; ok {
				if bytes.Equal(prior, raw) {
					continue
				}
				return nil, fmt.Errorf("instruction %q has conflicting roster source copies", instruction.ID)
			}
			selected[instruction.ID] = raw
			bodies = append(bodies, raw)
		}
	}
	return bodies, nil
}

func personalityLine(p *person.Person, role person.Role, bodies map[string][]byte) (string, error) {
	if len(role.Personalities) == 0 {
		return "Melded personalities: pending (#10).\n", nil
	}
	var parts []string
	var colors []string
	for _, name := range role.Personalities {
		binding := p.Personalities[name]
		colors = append(colors, binding.Color)
		entry := name
		if binding.Color != "" {
			entry += " (favorite color " + binding.Color + ")"
		}
		if _, ok := bodies[name]; ok {
			entry += ", defined in [" + name + "](personalities/" + name + ".md)"
		} else {
			entry += ", definition pending"
		}
		parts = append(parts, entry)
	}
	return "Melded personalities: " + strings.Join(parts, "; ") +
		". Melded favorite color: " + role.FavoriteColor + ".\n", nil
}

// personalityBodies pulls each bound skill's SKILL.md from the first source
// that provides it; absent bodies degrade to pending markers in the table.
func personalityBodies(p *person.Person, sources []*schema.Source) map[string][]byte {
	bodies := map[string][]byte{}
	for name, binding := range p.Personalities {
		for _, src := range sources {
			for _, skill := range src.Skills {
				if skill.ID != binding.Skill {
					continue
				}
				raw, err := src.ReadFile(filepath.ToSlash(filepath.Join(skill.Path, "SKILL.md")))
				if err == nil {
					bodies[name] = raw
				}
				break
			}
			if _, ok := bodies[name]; ok {
				break
			}
		}
	}
	return bodies
}

func sortedPersonalities(p *person.Person) []string {
	names := make([]string, 0, len(p.Personalities))
	for name := range p.Personalities {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
