// Package cascade is the absorbed v1 composer: it composes AGENTS.COMPOSE.md
// doctrine sources into COMPOSED files, wires harness load-point symlinks,
// and emits the compiled repository plan convergence consumers read.
package cascade

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/coilyco-flight-deck/agent-compose/v2/internal/layouts"
	"github.com/coilyco-flight-deck/agent-compose/v2/internal/roleslug"

	"gopkg.in/yaml.v3"

	"github.com/coilyco-flight-deck/agent-compose/v2/internal/personpolicy"
	"github.com/coilyco-flight-deck/agent-compose/v2/internal/telemetry"
)

const (
	Banner         = "<!-- generated by agent-compose from agent-compose.yaml; do not edit -->"
	manifestBanner = "generated by agent-compose from agent-compose.yaml; do not edit"
	sourceFilename = "AGENTS.COMPOSE.md"
)

type Config struct {
	Scopes               *scopeList          `yaml:"scopes"`
	Sources              []string            `yaml:"sources"`
	Roots                []string            `yaml:"roots"`
	LoadPoints           map[string]RawValue `yaml:"load_points"`
	PersonPolicy         string              `yaml:"person_policy"`
	PersonSource         string              `yaml:"person_source"`
	PersonalityLibraries []string            `yaml:"personality_libraries"`
	RosterSources        []string            `yaml:"roster_sources"`
	SkillLoadPoints      map[string]RawValue `yaml:"skill_load_points"`
	SkillCatalogManifest string              `yaml:"skill_catalog_manifest"`
	SkillRequests        []string            `yaml:"skill_requests"`
	OperatingContext     []string            `yaml:"operating_context"`
	SourceDelivery       string              `yaml:"source_delivery"`
	Appendix             []AppendixEntry     `yaml:"appendix"`
	Telemetry            *telemetry.Config   `yaml:"telemetry"`

	// Kept so a relative appendix path resolves against the config file.
	SourcePath string `yaml:"-"`
}

// AppendixEntry is one configured tail block: exactly one of Text or Path,
// and an empty Roles list makes it global.
type AppendixEntry struct {
	Text  string   `yaml:"text"`
	Path  string   `yaml:"path"`
	Roles []string `yaml:"roles"`
}

// scopeList accepts a scalar or a sequence, mirroring v1's normalizer; its
// presence (not emptiness) is what turns scope filtering on.
type scopeList []string

func (s *scopeList) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind == yaml.ScalarNode {
		*s = scopeList{node.Value}
		return nil
	}
	var values []string
	if err := node.Decode(&values); err != nil {
		return err
	}
	*s = values
	return nil
}

// RawValue keeps a load-point value's truthiness: null and false opt a
// harness out, a non-empty string sets its path.
type RawValue struct {
	node yaml.Node
}

func (r *RawValue) UnmarshalYAML(node *yaml.Node) error {
	r.node = *node
	return nil
}

func (r RawValue) truthy() bool {
	switch r.node.Tag {
	case "!!null":
		return false
	case "!!bool":
		return r.node.Value == "true"
	default:
		return r.node.Value != ""
	}
}

// LoadConfig reads one host config and fills the defaults that make a short
// file enough. See docs/cascade.md "Host config defaults".
func LoadConfig(path string) (*Config, error) {
	return loadConfig(path, defaultProjectsRoot())
}

func loadConfig(path, projects string) (*Config, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := decodeStrictYAML(raw, path, &cfg); err != nil {
		return nil, err
	}
	if err := personpolicy.Validate(cfg.PersonPolicy, cfg.PersonSource); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	seenRepositories := map[string]bool{}
	for _, repository := range cfg.OperatingContext {
		if err := validateConfiguredRepository(repository); err != nil {
			return nil, fmt.Errorf("%s: operating_context: %w", path, err)
		}
		if seenRepositories[repository] {
			return nil, fmt.Errorf("%s: operating_context repeats %q", path, repository)
		}
		seenRepositories[repository] = true
	}
	if err := validateAppendix(cfg.Appendix); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if err := cfg.Telemetry.Validate(); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	cfg.SourcePath = path
	applyDefaults(&cfg, path, projects)
	return &cfg, nil
}

// applyDefaults fills absent keys from the host and never overrides a set one.
// A default pointing at nothing on disk is skipped, not fatal. docs/cascade.md.
func applyDefaults(cfg *Config, path, projects string) {
	if cfg.Roots == nil {
		// The roster renders its personality library here, so a host with no
		// `roots` key still composes it. `roots: []` opts out.
		if root := filepath.Join(filepath.Dir(path), "sources"); isDir(root) {
			cfg.Roots = []string{root}
		}
	}
	if cfg.Sources == nil && projects != "" {
		// Delivery stays `inline` when sources are named, because only derived
		// ones are guaranteed to sit at the absolute path an import names.
		for _, identity := range cfg.OperatingContext {
			source := filepath.Join(projects, filepath.FromSlash(identity), "AGENTS.md")
			if isFile(source) {
				cfg.Sources = append(cfg.Sources, source)
			}
		}
		if len(cfg.Sources) > 0 && cfg.SourceDelivery == "" {
			cfg.SourceDelivery = DeliveryImport
		}
	}
	if cfg.SkillCatalogManifest == "" {
		if home, err := os.UserHomeDir(); err == nil {
			if manifest := filepath.Join(home, ".config", "aos", "catalogues.json"); isFile(manifest) {
				cfg.SkillCatalogManifest = manifest
			}
		}
	}
}

func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func isFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular()
}

// Shape is all cascade can check, because it never loads a person; see the
// appendix section of docs/cascade.md for how a dead slug surfaces.
var roleSlugRe = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

func validateAppendix(entries []AppendixEntry) error {
	for index, entry := range entries {
		position := index + 1
		hasText := strings.TrimSpace(entry.Text) != ""
		hasPath := strings.TrimSpace(entry.Path) != ""
		if hasText == hasPath {
			return fmt.Errorf("appendix entry %d needs exactly one of text or path", position)
		}
		seen := map[string]bool{}
		for _, role := range entry.Roles {
			if !roleSlugRe.MatchString(role) {
				return fmt.Errorf("appendix entry %d role %q must be a lowercase slug", position, role)
			}
			if seen[role] {
				return fmt.Errorf("appendix entry %d repeats role %q", position, role)
			}
			seen[role] = true
		}
	}
	return nil
}

// AppendixBlock is a resolved entry: provenance fence, body, binding roles.
type AppendixBlock struct {
	Fence string
	Body  string
	Roles []string
}

// GatherAppendix resolves entries in listed order, returning the error
// strings GatherSources uses so a missing file warns rather than aborts.
func GatherAppendix(cfg *Config) ([]AppendixBlock, []string) {
	var blocks []AppendixBlock
	var errors []string
	for index, entry := range cfg.Appendix {
		position := index + 1
		roles := append([]string(nil), entry.Roles...)
		if text := strings.Trim(entry.Text, "\n"); strings.TrimSpace(text) != "" {
			blocks = append(blocks, AppendixBlock{
				Fence: appendixFence(fmt.Sprintf("agent-compose.yaml entry %d", position), roles),
				Body:  text,
				Roles: roles,
			})
			continue
		}
		resolved := ResolveConfiguredPath(expand(entry.Path), cfg.SourcePath, homeDir())
		info, err := os.Stat(resolved)
		if err != nil || info.IsDir() {
			errors = append(errors, fmt.Sprintf("appendix path not found: %s", resolved))
			continue
		}
		_, body, err := parseSource(resolved)
		if err != nil {
			errors = append(errors, fmt.Sprintf("read appendix %s: %v", resolved, err))
			continue
		}
		body = absolutizeLinks(stripNavigationSections(strings.Trim(body, "\n")), filepath.Dir(resolved))
		blocks = append(blocks, AppendixBlock{
			Fence: appendixFence(resolved, roles),
			Body:  body,
			Roles: roles,
		})
	}
	return blocks, errors
}

func appendixFence(origin string, roles []string) string {
	if len(roles) == 0 {
		return fmt.Sprintf("<!-- appendix: %s -->", origin)
	}
	return fmt.Sprintf("<!-- appendix: %s (roles: %s) -->", origin, strings.Join(roles, ", "))
}

func homeDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return home
}

// path.Clean, not filepath.Clean: these are logical owner/repository
// identifiers, and filepath.Clean rejects every one of them on Windows.
func validateConfiguredRepository(value string) error {
	if value == "" || strings.Contains(value, `\`) || strings.HasPrefix(value, "/") || path.Clean(value) != value {
		return fmt.Errorf("repository %q must be a clean owner/repository path", value)
	}
	parts := strings.Split(value, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return fmt.Errorf("repository %q must have owner/repository form", value)
	}
	return nil
}

func decodeStrictYAML(raw []byte, path string, value any) error {
	decoder := yaml.NewDecoder(bytes.NewReader(raw))
	decoder.KnownFields(true)
	if err := decoder.Decode(value); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return fmt.Errorf("%s: trailing YAML document", path)
	}
	return nil
}

func expand(path string) string {
	if path == "~" || strings.HasPrefix(path, "~/") {
		home, err := os.UserHomeDir()
		if err == nil {
			return filepath.Join(home, strings.TrimPrefix(strings.TrimPrefix(path, "~"), "/"))
		}
	}
	return path
}

// ResolveConfiguredPath expands one host-config path against its config file
// and injectable home directory.
func ResolveConfiguredPath(value, configPath, home string) string {
	value = strings.TrimSpace(value)
	if value == "~" || strings.HasPrefix(value, "~/") {
		return filepath.Join(home, strings.TrimPrefix(strings.TrimPrefix(value, "~"), "/"))
	}
	if filepath.IsAbs(value) {
		return value
	}
	return filepath.Join(filepath.Dir(configPath), value)
}

// DefaultLoadPoints is each cascade harness's home native instructions path
// from the layouts table. Config opts others in.
func DefaultLoadPoints() (map[string]string, error) {
	return cascadePoints(func(points *layouts.LoadPoints) string { return points.Instructions })
}

// ResolveLoadPoints merges config overrides over the defaults; falsy values
// (null, false, empty) opt a harness out entirely.
func ResolveLoadPoints(cfg *Config) (map[string]string, error) {
	points, err := DefaultLoadPoints()
	if err != nil {
		return nil, err
	}
	return resolvePoints(points, cfg.LoadPoints, func(p *layouts.LoadPoints) string { return p.Instructions })
}

// OperatingBase renders the base for one harness and role: the load point's
// own sources, plus each appendix block bound to that role.
func OperatingBase(cfg *Config, harness, role string) (string, error) {
	body, tail, err := OperatingBaseParts(cfg, harness, role)
	if err != nil {
		return "", err
	}
	if tail == "" {
		return body, nil
	}
	return body + "\n" + tail, nil
}

// AppendixRoles returns every distinct role slug the appendix scopes a block to,
// sorted. Cascade never loads a person, so a caller that has one checks these.
func AppendixRoles(cfg *Config) ([]string, error) {
	appendix, errs := GatherAppendix(cfg)
	if len(errs) > 0 {
		return nil, fmt.Errorf("appendix roles: %s", strings.Join(errs, "; "))
	}
	seen := map[string]bool{}
	var roles []string
	for _, block := range appendix {
		for _, role := range block.Roles {
			role = roleslug.Canonical(role)
			if seen[role] {
				continue
			}
			seen[role] = true
			roles = append(roles, role)
		}
	}
	sort.Strings(roles)
	return roles, nil
}

// OperatingBaseParts splits that render into sources and appendix, for a caller
// that rewrites the sources before rendering them. See ComposeParts.
func OperatingBaseParts(cfg *Config, harness, role string) (string, string, error) {
	if err := ValidateSources(cfg); err != nil {
		return "", "", err
	}
	gathered, _ := GatherSources(cfg)
	filtering := cfg.Scopes != nil
	var machineScopes []string
	if filtering {
		machineScopes = *cfg.Scopes
	}
	selected := selectByHarness(SelectByScope(gathered, machineScopes, filtering), harness)
	if len(selected) == 0 {
		return "", "", fmt.Errorf("no operating-base sources matched harness %q", harness)
	}
	overrides := map[string]string{}
	for _, src := range selected {
		if override := discoverOverride(src, harness); override != "" {
			overrides[src] = override
		}
	}
	appendix, errs := GatherAppendix(cfg)
	if len(errs) > 0 {
		return "", "", fmt.Errorf("operating base: %s", strings.Join(errs, "; "))
	}
	return ComposePartsScoped(
		selected, overrides, appendix, role, cfg.SourceDelivery, ConfiguredSources(cfg))
}

// DefaultSkillLoadPoints mirrors DefaultLoadPoints for skills. A harness reads
// only its own table entry; see docs/projection.md.
func DefaultSkillLoadPoints() (map[string]string, error) {
	return cascadePoints(func(points *layouts.LoadPoints) string { return points.SkillsDir })
}

// ResolveSkillLoadPoints merges config overrides over the skill defaults, with
// the same falsy opt-out as ResolveLoadPoints.
func ResolveSkillLoadPoints(cfg *Config) (map[string]string, error) {
	points, err := DefaultSkillLoadPoints()
	if err != nil {
		return nil, err
	}
	return resolvePoints(points, cfg.SkillLoadPoints, func(p *layouts.LoadPoints) string { return p.SkillsDir })
}

func cascadePoints(pick func(*layouts.LoadPoints) string) (map[string]string, error) {
	table, err := layouts.Load()
	if err != nil {
		return nil, err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return map[string]string{}, nil
	}
	points := map[string]string{}
	for name, harness := range table {
		if harness.Cascade {
			points[name] = filepath.Join(home, filepath.FromSlash(pick(harness.Home.Native)))
		}
	}
	return points, nil
}

// A bare `true` opts a harness in at its table default, which is how a harness
// outside the cascade set (opencode) joins without restating its path.
func resolvePoints(
	points map[string]string, overrides map[string]RawValue, pick func(*layouts.LoadPoints) string,
) (map[string]string, error) {
	for harness, value := range overrides {
		switch {
		case !value.truthy():
			delete(points, harness)
		case value.node.Tag == "!!bool":
			fallback, err := tableDefault(harness, pick)
			if err != nil {
				return nil, err
			}
			points[harness] = fallback
		default:
			points[harness] = expand(value.node.Value)
		}
	}
	return points, nil
}

func tableDefault(harness string, pick func(*layouts.LoadPoints) string) (string, error) {
	table, err := layouts.Load()
	if err != nil {
		return "", err
	}
	entry, ok := table[harness]
	if !ok || entry.Home.Native == nil {
		return "", fmt.Errorf("load point %q: no harness of that name has a home load point to default to", harness)
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, filepath.FromSlash(pick(entry.Home.Native))), nil
}

// splitFrontmatter separates a leading `--- ... ---` YAML block from the
// body; malformed fences or YAML degrade to no metadata, as in v1.
func splitFrontmatter(text string) (map[string]any, string) {
	lines := strings.Split(text, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return map[string]any{}, text
	}
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != "---" {
			continue
		}
		var meta map[string]any
		if err := yaml.Unmarshal([]byte(strings.Join(lines[1:i], "\n")), &meta); err != nil || meta == nil {
			meta = map[string]any{}
		}
		return meta, strings.Join(lines[i+1:], "\n")
	}
	return map[string]any{}, text
}

func normalizeScopes(value any) []string {
	switch v := value.(type) {
	case string:
		return []string{v}
	case []any:
		out := make([]string, 0, len(v))
		for _, item := range v {
			out = append(out, fmt.Sprint(item))
		}
		return out
	default:
		return nil
	}
}

// parseSource returns a source's declared scopes and frontmatter-stripped body.
func parseSource(path string) ([]string, string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, "", err
	}
	meta, body := splitFrontmatter(string(raw))
	return normalizeScopes(meta["scopes"]), body, nil
}

func sourceHarnesses(path string) ([]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	meta, _ := splitFrontmatter(string(raw))
	return normalizeScopes(meta["harnesses"]), nil
}

// discoverSources finds AGENTS.COMPOSE.md under root, skipping dot-dirs,
// sorted for determinism.
func discoverSources(root string) ([]string, error) {
	var found []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && strings.HasPrefix(d.Name(), ".") && p != root {
			return filepath.SkipDir
		}
		if !d.IsDir() && d.Name() == sourceFilename {
			found = append(found, p)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(found)
	return found, nil
}

// An empty segment or a live template marker means a variable did not resolve,
// which otherwise reports as a path typo. See docs/cascade.md.
func unresolvedSegment(raw string) string {
	switch {
	case strings.Contains(raw, "{{"), strings.Contains(raw, "${"):
		return "an unrendered template marker"
	case strings.Contains(strings.TrimPrefix(raw, "/"), "//"):
		return "an empty path segment"
	}
	return ""
}

// ValidateSources refuses a named source that cannot carry doctrine. Discovered
// `roots` entries stay lenient, because nothing declared those. docs/cascade.md.
func ValidateSources(cfg *Config) error {
	importing := cfg.SourceDelivery == DeliveryImport
	for _, raw := range cfg.Sources {
		src := expand(raw)
		if importing && !filepath.IsAbs(src) {
			return fmt.Errorf("import source %s must be absolute", src)
		}
		if segment := unresolvedSegment(raw); segment != "" {
			return fmt.Errorf(
				"source %s has %s, so a config template resolved empty rather than the path being wrong",
				raw, segment)
		}
		info, err := os.Stat(src)
		if err != nil {
			return fmt.Errorf("source %s: %w", src, err)
		}
		if info.IsDir() {
			return fmt.Errorf("source %s is a directory", src)
		}
		if info.Size() == 0 {
			return fmt.Errorf("source %s is empty", src)
		}
	}
	return nil
}

// ConfiguredSources keys the named `sources` entries by absolute path. Only
// these can be delivered twice, so only these answer to `source_delivery`.
func ConfiguredSources(cfg *Config) map[string]bool {
	named := make(map[string]bool, len(cfg.Sources))
	for _, raw := range cfg.Sources {
		key, err := filepath.Abs(expand(raw))
		if err != nil {
			continue
		}
		named[key] = true
	}
	return named
}

// GatherSources resolves explicit entries in listed order, then discovered
// root entries sorted; duplicates collapse to first occurrence.
func GatherSources(cfg *Config) ([]string, []string) {
	var errors []string
	var ordered []string
	seen := map[string]bool{}
	add := func(path string) {
		key, err := filepath.Abs(path)
		if err != nil {
			key = path
		}
		if !seen[key] {
			seen[key] = true
			ordered = append(ordered, path)
		}
	}
	for _, raw := range cfg.Sources {
		src := expand(raw)
		if info, err := os.Stat(src); err != nil || info.IsDir() {
			errors = append(errors, fmt.Sprintf("source not found: %s", src))
			continue
		}
		add(src)
	}
	for _, raw := range cfg.Roots {
		root := expand(raw)
		if info, err := os.Stat(root); err != nil || !info.IsDir() {
			errors = append(errors, fmt.Sprintf("root is not a directory: %s", root))
			continue
		}
		found, err := discoverSources(root)
		if err != nil {
			errors = append(errors, fmt.Sprintf("walk %s: %v", root, err))
			continue
		}
		for _, src := range found {
			add(src)
		}
	}
	return ordered, errors
}

// SelectByScope keeps sources whose scopes intersect the machine's; nil
// machine scopes disables filtering, and untagged sources drop under it.
func SelectByScope(sources []string, machineScopes []string, filtering bool) []string {
	if !filtering {
		return sources
	}
	wanted := map[string]bool{}
	for _, s := range machineScopes {
		wanted[s] = true
	}
	var kept []string
	for _, path := range sources {
		scopes, _, err := parseSource(path)
		if err != nil {
			continue
		}
		for _, s := range scopes {
			if wanted[s] {
				kept = append(kept, path)
				break
			}
		}
	}
	return kept
}

func selectByHarness(sources []string, harness string) []string {
	var kept []string
	for _, path := range sources {
		allowed, err := sourceHarnesses(path)
		if err != nil {
			continue
		}
		if allowed == nil || contains(allowed, harness) {
			kept = append(kept, path)
		}
	}
	return kept
}

// discoverOverride finds the sibling AGENTS.<harness>.md beside a base
// source; the directory binds it, so it can only patch that base.
func discoverOverride(base, harness string) string {
	candidate := filepath.Join(filepath.Dir(base), "AGENTS."+harness+".md")
	if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
		return candidate
	}
	return ""
}

func contains(list []string, item string) bool {
	for _, entry := range list {
		if entry == item {
			return true
		}
	}
	return false
}
