package palette

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/coilyco/agent-compose/v2/internal/color"
	"github.com/coilyco/agent-compose/v2/internal/person"
)

// SnapshotPath is the committed record of the derived role palette, relative
// to the repository root.
const SnapshotPath = "internal/palette/role-palette.txt"

// RenderSnapshot writes the derived role colors, so a roster edit arrives as a
// reviewable diff rather than silent drift across every rendered surface.
func RenderSnapshot(p *person.Person) ([]byte, error) {
	if p == nil {
		return nil, fmt.Errorf("render role palette: person is nil")
	}
	favorites := make([]string, 0, len(p.RoleOrder))
	backgrounds := make([]string, 0, len(p.RoleOrder))
	for _, name := range p.RoleOrder {
		if p.Roles[name].ColorTwin != "" {
			continue
		}
		favorites = append(favorites, p.Roles[name].FavoriteColor)
		backgrounds = append(backgrounds, p.Roles[name].Background)
	}
	separation, err := color.MinSeparation(favorites)
	if err != nil {
		return nil, fmt.Errorf("render role palette: %w", err)
	}
	backgroundSeparation, err := color.MinSeparation(backgrounds)
	if err != nil {
		return nil, fmt.Errorf("render role palette: %w", err)
	}

	var out bytes.Buffer
	out.WriteString("Generated by `agent-compose palette-snapshot`. Do not edit.\n\n")
	out.WriteString("Each role's favorite color is derived from the whole roster at once, not\n")
	out.WriteString("from its own personalities alone. Roles that share personalities have\n")
	out.WriteString("nearly identical component means, so a per-role average cannot tell them\n")
	out.WriteString("apart.\n\n")
	out.WriteString("Two stages. Each role first blends its components weighted by how few other\n")
	out.WriteString("roles share them, so whatever distinguishes a role leads its color. Then\n")
	out.WriteString("every role is pushed away from its nearest neighbor to grow the smallest\n")
	out.WriteString("pairwise distance, bounded by a drift cap so no color leaves its own blend,\n")
	out.WriteString("and clamped back into the terminal-legible band. Iteration order is fixed\n")
	out.WriteString("and nothing is random, so one roster always derives one palette.\n\n")
	out.WriteString("Roster loading asserts a floor on the closest pair. Two roles melding the\n")
	out.WriteString("same personalities derive barely 0.06 apart and fail it.\n\n")
	out.WriteString("The derivation is global, so editing one role can move every color below.\n")
	out.WriteString("That is why this file is committed: the change arrives as a diff.\n\n")
	out.WriteString("The window background is a second derivation from the same set. Accents\n")
	out.WriteString("live in the legible band, so tinting one into a near-black leaves seven\n")
	out.WriteString("backgrounds nobody can tell apart. Each role's hue is held and moved onto\n")
	out.WriteString("equal spacing at a fixed low lightness and chroma, at the rotation offset\n")
	out.WriteString("that turns every role the least. agentic-os#1245, #358.\n\n")
	out.WriteString("Lightness buys that spacing and chroma does not. Adjacent hues sit closer\n")
	out.WriteString("as the roster grows, and more chroma at a low lightness pushes them out of\n")
	out.WriteString("sRGB where they clamp back together. Measured while adding the tenth seat:\n")
	out.WriteString("at L 0.235 the closest pair fell to 0.0267 against a 0.0300 floor, raising\n")
	out.WriteString("chroma to 0.070 recovered only 0.0025, and L 0.260 cleared it outright.\n\n")
	out.WriteString("Both levers are finite, though, and the eleventh seat (junior-sysadmin)\n")
	out.WriteString("reached them: pushing lightness to the test suite's own legibility ceiling\n")
	out.WriteString("(L 0.32) and chroma to 0.065 cleared the floor by only 0.0010. Full details\n")
	out.WriteString("and the actual numbers at each setting tried: teable:coilyco-flight-deck/agent-compose#7847.\n\n")
	out.WriteString("A role naming `color_twin` sits out of both derivations entirely and copies\n")
	out.WriteString("its named role's favorite and background verbatim, so it never enters the\n")
	out.WriteString("spread-apart solve or the distinctness floor above - the point when two roles\n")
	out.WriteString("are meant to read as one identity at different tiers, not two neighbors that\n")
	out.WriteString("happen to be close. junior-sysadmin twins senior-sysadmin this way, which is\n")
	out.WriteString("why the roster below still solves as ten independent points, not eleven, and\n")
	out.WriteString("the L/chroma push above never actually had to ship.\n\n")
	fmt.Fprintf(&out, "Closest accent pair: %.4f\n", separation)
	fmt.Fprintf(&out, "Closest background pair: %.4f\n\n", backgroundSeparation)
	for _, name := range p.RoleOrder {
		role := p.Roles[name]
		twin := ""
		if role.ColorTwin != "" {
			twin = fmt.Sprintf(" // twin of %s", role.ColorTwin)
		}
		fmt.Fprintf(
			&out,
			"%s // %s // %s // %s%s\n",
			name,
			role.FavoriteColor,
			role.Background,
			strings.Join(role.Personalities, ", "),
			twin,
		)
	}
	return out.Bytes(), nil
}

// CheckSnapshot reports whether the committed page still matches the roster.
func CheckSnapshot(path string, rendered []byte) error {
	committed, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if !bytes.Equal(committed, rendered) {
		return fmt.Errorf(
			"%s is stale: run `agent-compose palette-snapshot` and stage the result",
			path,
		)
	}
	return nil
}

// WriteSnapshot replaces the committed page.
func WriteSnapshot(path string, rendered []byte) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, rendered, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
